/* Author:Zeshan Amjad */

// Wrap in a self-invoking-anonymous function, passing jQuery as an argument

(function($){

	$(document).ready(function() {

		// Raw maps of ISO codes for countries + populations
		var countries = [
			{name: 'Afghanistan', code: 'AF'},
			{name: 'Åland Islands', code: 'AX'},
			{name: 'Albania', code: 'AL'},
			{name: 'Algeria', code: 'DZ'},
			{name: 'American Samoa', code: 'AS'},
			{name: 'AndorrA', code: 'AD'},
			{name: 'Angola', code: 'AO'},
			{name: 'Anguilla', code: 'AI'},
			{name: 'Antarctica', code: 'AQ'},
			{name: 'Antigua and Barbuda', code: 'AG'},
			{name: 'Argentina', code: 'AR'},
			{name: 'Armenia', code: 'AM'},
			{name: 'Aruba', code: 'AW'},
			{name: 'Australia', code: 'AU'},
			{name: 'Austria', code: 'AT'},
			{name: 'Azerbaijan', code: 'AZ'},
			{name: 'Bahamas', code: 'BS'},
			{name: 'Bahrain', code: 'BH'},
			{name: 'Bangladesh', code: 'BD'},
			{name: 'Barbados', code: 'BB'},
			{name: 'Belarus', code: 'BY'},
			{name: 'Belgium', code: 'BE'},
			{name: 'Belize', code: 'BZ'},
			{name: 'Benin', code: 'BJ'},
			{name: 'Bermuda', code: 'BM'},
			{name: 'Bhutan', code: 'BT'},
			{name: 'Bolivia', code: 'BO'},
			{name: 'Bosnia and Herzegovina', code: 'BA'},
			{name: 'Botswana', code: 'BW'},
			{name: 'Bouvet Island', code: 'BV'},
			{name: 'Brazil', code: 'BR'},
			{name: 'British Indian Ocean Territory', code: 'IO'},
			{name: 'Brunei Darussalam', code: 'BN'},
			{name: 'Bulgaria', code: 'BG'},
			{name: 'Burkina Faso', code: 'BF'},
			{name: 'Burundi', code: 'BI'},
			{name: 'Cambodia', code: 'KH'},
			{name: 'Cameroon', code: 'CM'},
			{name: 'Canada', code: 'CA'},
			{name: 'Cape Verde', code: 'CV'},
			{name: 'Cayman Islands', code: 'KY'},
			{name: 'Central African Republic', code: 'CF'},
			{name: 'Chad', code: 'TD'},
			{name: 'Chile', code: 'CL'},
			{name: 'People\'s Republic of China', code: 'CN'},
			{name: 'Christmas Island', code: 'CX'},
			{name: 'Cocos (Keeling) Islands', code: 'CC'},
			{name: 'Colombia', code: 'CO'},
			{name: 'Comoros', code: 'KM'},
			{name: 'Congo', code: 'CG'},
			{name: 'Congo, The Democratic Republic of the', code: 'CD'},
			{name: 'Cook Islands', code: 'CK'},
			{name: 'Costa Rica', code: 'CR'},
			{name: 'Cote D\'Ivoire', code: 'CI'},
			{name: 'Croatia', code: 'HR'},
			{name: 'Cuba', code: 'CU'},
			{name: 'Cyprus', code: 'CY'},
			{name: 'Czech Republic', code: 'CZ'},
			{name: 'Denmark', code: 'DK'},
			{name: 'Djibouti', code: 'DJ'},
			{name: 'Dominica', code: 'DM'},
			{name: 'Dominican Republic', code: 'DO'},
			{name: 'Ecuador', code: 'EC'},
			{name: 'Egypt', code: 'EG'},
			{name: 'El Salvador', code: 'SV'},
			{name: 'Equatorial Guinea', code: 'GQ'},
			{name: 'Eritrea', code: 'ER'},
			{name: 'Estonia', code: 'EE'},
			{name: 'Ethiopia', code: 'ET'},
			{name: 'Falkland Islands (Malvinas)', code: 'FK'},
			{name: 'Faroe Islands', code: 'FO'},
			{name: 'Fiji', code: 'FJ'},
			{name: 'Finland', code: 'FI'},
			{name: 'France', code: 'FR'},
			{name: 'French Guiana', code: 'GF'},
			{name: 'French Polynesia', code: 'PF'},
			{name: 'French Southern Territories', code: 'TF'},
			{name: 'Gabon', code: 'GA'},
			{name: 'Gambia', code: 'GM'},
			{name: 'Georgia', code: 'GE'},
			{name: 'Germany', code: 'DE'},
			{name: 'Ghana', code: 'GH'},
			{name: 'Gibraltar', code: 'GI'},
			{name: 'Great Britain', code: 'GB'},
			{name: 'Greece', code: 'GR'},
			{name: 'Greenland', code: 'GL'},
			{name: 'Grenada', code: 'GD'},
			{name: 'Guadeloupe', code: 'GP'},
			{name: 'Guam', code: 'GU'},
			{name: 'Guatemala', code: 'GT'},
			{name: 'Guernsey', code: 'GG'},
			{name: 'Guinea', code: 'GN'},
			{name: 'Guinea-Bissau', code: 'GW'},
			{name: 'Guyana', code: 'GY'},
			{name: 'Haiti', code: 'HT'},
			{name: 'Heard Island and Mcdonald Islands', code: 'HM'},
			{name: 'Holy See (Vatican City State)', code: 'VA'},
			{name: 'Honduras', code: 'HN'},
			{name: 'Hong Kong, China', code: 'HK'},
			{name: 'Hungary', code: 'HU'},
			{name: 'Iceland', code: 'IS'},
			{name: 'India', code: 'IN'},
			{name: 'Indonesia', code: 'ID'},
			{name: 'Islamic Republic Of Iran', code: 'IR'},
			{name: 'Iraq', code: 'IQ'},
			{name: 'Ireland', code: 'IE'},
			{name: 'Isle of Man', code: 'IM'},
			{name: 'Israel', code: 'IL'},
			{name: 'Italy', code: 'IT'},
			{name: 'Jamaica', code: 'JM'},
			{name: 'Japan', code: 'JP'},
			{name: 'Jersey', code: 'JE'},
			{name: 'Jordan', code: 'JO'},
			{name: 'Kazakhstan', code: 'KZ'},
			{name: 'Kenya', code: 'KE'},
			{name: 'Kiribati', code: 'KI'},
			{name: 'Democratic People\'s Republic of Korea', code: 'KP'},
			{name: 'Republic of Korea', code: 'KR'},
			{name: 'Kuwait', code: 'KW'},
			{name: 'Kyrgyzstan', code: 'KG'},
			{name: 'Lao People\'s Democratic Republic', code: 'LA'},
			{name: 'Latvia', code: 'LV'},
			{name: 'Lebanon', code: 'LB'},
			{name: 'Lesotho', code: 'LS'},
			{name: 'Liberia', code: 'LR'},
			{name: 'Libyan Arab Jamahiriya', code: 'LY'},
			{name: 'Liechtenstein', code: 'LI'},
			{name: 'Lithuania', code: 'LT'},
			{name: 'Luxembourg', code: 'LU'},
			{name: 'Macao', code: 'MO'},
			{name: 'The Former Yugoslav Republic of Macedonia', code: 'MK'},
			{name: 'Madagascar', code: 'MG'},
			{name: 'Malawi', code: 'MW'},
			{name: 'Malaysia', code: 'MY'},
			{name: 'Maldives', code: 'MV'},
			{name: 'Mali', code: 'ML'},
			{name: 'Malta', code: 'MT'},
			{name: 'Marshall Islands', code: 'MH'},
			{name: 'Martinique', code: 'MQ'},
			{name: 'Mauritania', code: 'MR'},
			{name: 'Mauritius', code: 'MU'},
			{name: 'Mayotte', code: 'YT'},
			{name: 'Mexico', code: 'MX'},
			{name: 'Federated States of Micronesia', code: 'FM'},
			{name: 'Republic of Moldova', code: 'MD'},
			{name: 'Monaco', code: 'MC'},
			{name: 'Mongolia', code: 'MN'},
			{name: 'Montserrat', code: 'MS'},
			{name: 'Morocco', code: 'MA'},
			{name: 'Mozambique', code: 'MZ'},
			{name: 'Myanmar', code: 'MM'},
			{name: 'Namibia', code: 'NA'},
			{name: 'Nauru', code: 'NR'},
			{name: 'Nepal', code: 'NP'},
			{name: 'Netherlands', code: 'NL'},
			{name: 'Netherlands Antilles', code: 'AN'},
			{name: 'New Caledonia', code: 'NC'},
			{name: 'New Zealand', code: 'NZ'},
			{name: 'Nicaragua', code: 'NI'},
			{name: 'Niger', code: 'NE'},
			{name: 'Nigeria', code: 'NG'},
			{name: 'Niue', code: 'NU'},
			{name: 'Norfolk Island', code: 'NF'},
			{name: 'Northern Mariana Islands', code: 'MP'},
			{name: 'Norway', code: 'NO'},
			{name: 'Oman', code: 'OM'},
			{name: 'Pakistan', code: 'PK'},
			{name: 'Palau', code: 'PW'},
			{name: 'Palestinian Territory, Occupied', code: 'PS'},
			{name: 'Panama', code: 'PA'},
			{name: 'Papua New Guinea', code: 'PG'},
			{name: 'Paraguay', code: 'PY'},
			{name: 'Peru', code: 'PE'},
			{name: 'Philippines', code: 'PH'},
			{name: 'Pitcairn', code: 'PN'},
			{name: 'Poland', code: 'PL'},
			{name: 'Portugal', code: 'PT'},
			{name: 'Puerto Rico', code: 'PR'},
			{name: 'Qatar', code: 'QA'},
			{name: 'Reunion', code: 'RE'},
			{name: 'Romania', code: 'RO'},
			{name: 'Russian Federation', code: 'RU'},
			{name: 'RWANDA', code: 'RW'},
			{name: 'Saint Helena', code: 'SH'},
			{name: 'Saint Kitts and Nevis', code: 'KN'},
			{name: 'Saint Lucia', code: 'LC'},
			{name: 'Saint Pierre and Miquelon', code: 'PM'},
			{name: 'Saint Vincent and the Grenadines', code: 'VC'},
			{name: 'Samoa', code: 'WS'},
			{name: 'San Marino', code: 'SM'},
			{name: 'Sao Tome and Principe', code: 'ST'},
			{name: 'Saudi Arabia', code: 'SA'},
			{name: 'Senegal', code: 'SN'},
			{name: 'Serbia', code: 'CS'},
			{name: 'Seychelles', code: 'SC'},
			{name: 'Sierra Leone', code: 'SL'},
			{name: 'Singapore', code: 'SG'},
			{name: 'Slovakia', code: 'SK'},
			{name: 'Slovenia', code: 'SI'},
			{name: 'Solomon Islands', code: 'SB'},
			{name: 'Somalia', code: 'SO'},
			{name: 'South Africa', code: 'ZA'},
			{name: 'South Georgia and the South Sandwich Islands', code: 'GS'},
			{name: 'Spain', code: 'ES'},
			{name: 'Sri Lanka', code: 'LK'},
			{name: 'Sudan', code: 'SD'},
			{name: 'Suriname', code: 'SR'},
			{name: 'Svalbard and Jan Mayen', code: 'SJ'},
			{name: 'Swaziland', code: 'SZ'},
			{name: 'Sweden', code: 'SE'},
			{name: 'Switzerland', code: 'CH'},
			{name: 'Syrian Arab Republic', code: 'SY'},
			{name: 'Taipei (Chinese Taipei)', code: 'TW'},
			{name: 'Tajikistan', code: 'TJ'},
			{name: 'Tanzania, United Republic of', code: 'TZ'},
			{name: 'Thailand', code: 'TH'},
			{name: 'Timor-Leste', code: 'TL'},
			{name: 'Togo', code: 'TG'},
			{name: 'Tokelau', code: 'TK'},
			{name: 'Tonga', code: 'TO'},
			{name: 'Trinidad and Tobago', code: 'TT'},
			{name: 'Tunisia', code: 'TN'},
			{name: 'Turkey', code: 'TR'},
			{name: 'Turkmenistan', code: 'TM'},
			{name: 'Turks and Caicos Islands', code: 'TC'},
			{name: 'Tuvalu', code: 'TV'},
			{name: 'Uganda', code: 'UG'},
			{name: 'Ukraine', code: 'UA'},
			{name: 'United Arab Emirates', code: 'AE'},
			{name: 'United Kingdom', code: 'GB'},
			{name: 'United States of America', code: 'US'},
			{name: 'United States Minor Outlying Islands', code: 'UM'},
			{name: 'Uruguay', code: 'UY'},
			{name: 'Uzbekistan', code: 'UZ'},
			{name: 'Vanuatu', code: 'VU'},
			{name: 'Venezuela', code: 'VE'},
			{name: 'Viet Nam', code: 'VN'},
			{name: 'Virgin Islands, British', code: 'VG'},
			{name: 'Virgin Islands, U.S.', code: 'VI'},
			{name: 'Wallis and Futuna', code: 'WF'},
			{name: 'Western Sahara', code: 'EH'},
			{name: 'Yemen', code: 'YE'},
			{name: 'Zambia', code: 'ZM'},
			{name: 'Zimbabwe', code: 'ZW'}
		],
		population = {
			'People\'s Republic of China': 1347350000,
			'India': 1210193422,
			'United States of America': 314047000,
			'Indonesia': 237641326,
			'Brazil': 192376496,
			'Pakistan': 180300000,
			'Nigeria': 166629000,
			'Bangladesh': 152518015,
			'Russian Federation': 143117000,
			'Japan': 127530000,
			'Mexico': 112336538,
			'Philippines': 92337852,
			'Vietnam': 87840000,
			'Ethiopia': 84320987,
			'Egypt': 82463000,
			'Germany': 81859000,
			'Islamic Republic of Iran': 75149669,
			'Turkey': 74724269,
			'Democratic Republic of the Congo': 69575000,
			'Thailand': 65479453,
			'France': 65350000,
			'Great Britain': 62262000,
			'Italy': 60813326,
			'South Africa': 50586757,
			'Myanmar': 48724000,
			'Republic of Korea': 48580000,
			'Colombia': 46635000,
			'Spain': 46185697,
			'Ukraine': 45589171,
			'Tanzania': 43188000,
			'Kenya': 42749000,
			'Argentina': 40117096,
			'Poland': 38501000,
			'Algeria': 37100000,
			'Canada': 34878500,
			'Iraq': 33330000,
			'Uganda': 32939800,
			'Morocco': 32631200,
			'Sudan': 30894000,
			'Peru': 30135875,
			'Uzbekistan': 29123400,
			'Malaysia': 28334135,
			'Venezuela': 27150095,
			'Saudi Arabia': 27136977,
			'Nepal': 26620809,
			'Afghanistan': 25500100,
			'Ghana': 24658823,
			'Democratic People\'s Republic of Korea': 24554000,
			'Yemen': 24527000,
			'Mozambique': 23700715,
			'Taipei (Chinese Taipei)': 23261747,
			'Australia': 22690653,
			'Syria': 21688000,
			'Madagascar': 20696070,
			'Angola': 20609294,
			'Ivory Coast': 20595000,
			'Sri Lanka': 20277597,
			'Cameroon': 19406100,
			'Romania': 19042936,
			'Chile': 17402630,
			'Netherlands': 16736075,
			'Kazakhstan': 16734000,
			'Mali': 16319000,
			'Niger': 16274738,
			'Malawi': 15883000,
			'Burkina Faso': 15730977,
			'Guatemala': 14713763,
			'Ecuador': 14483499,
			'Cambodia': 14478000,
			'Zambia': 13046508,
			'Zimbabwe': 13014000,
			'Senegal': 12855153,
			'Chad': 11831000,
			'Cuba': 11247925,
			'Belgium': 10951266,
			'Greece': 10787690,
			'Rwanda': 10718379,
			'Tunisia': 10673800,
			'Portugal': 10561614,
			'Czech Republic': 10504203,
			'Guinea': 10481000,
			'Bolivia': 10426154,
			'Haiti': 10085214,
			'Hungary': 9962000,
			'Somalia': 9797000,
			'Sweden': 9495113,
			'Belarus': 9458500,
			'Dominican Republic': 9445281,
			'Benin': 9352000,
			'Azerbaijan': 9235100,
			'Burundi': 8749000,
			'Austria': 8452835,
			'Honduras': 8385072,
			'United Arab Emirates': 8264070,
			'South Sudan': 8260490,
			'Switzerland': 7952600,
			'Israel': 7879500,
			'Tajikistan': 7800000,
			'Bulgaria': 7364570,
			'Serbia': 7120666,
			'Hong Kong, China':  7103700,
			'Papua New Guinea': 7014000,
			'Libya': 6469000,
			'Laos': 6465800,
			'Paraguay': 6337127,
			'Jordan': 6331000,
			'Togo': 6191155,
			'El Salvador': 6183000,
			'Sierra Leone': 6126000,
			'Nicaragua': 5815524,
			'Denmark': 5584758,
			'Eritrea': 5581000,
			'Kyrgyzstan': 5477600,
			'Slovakia': 5445324,
			'Finland': 5413730,
			'Singapore': 5183700,
			'Turkmenistan': 5170000,
			'Norway': 5027400,
			'Ireland': 4588252,
			'Central African Republic': 4576000,
			'Georgia': 4497600,
			'New Zealand': 4434340,
			'Costa Rica': 4301712,
			'Palestinian territories': 4293309,
			'Lebanon': 4292000,
			'Croatia': 4290612,
			'Liberia': 4245000,
			'Republic of the Congo': 4140000,
			'Bosnia and Herzegovina': 3839737,
			'Puerto Rico':  3725789,
			'Kuwait': 3582054,
			'Republic of Moldova': 3559500,
			'Panama': 3405813,
			'Mauritania': 3378254,
			'Armenia': 3268500,
			'Uruguay': 3251526,
			'Lithuania': 3187700,
			'Mongolia': 2844000,
			'Albania': 2831741,
			'Oman': 2773479,
			'Jamaica': 2705827,
			'Namibia': 2364000,
			'Lesotho': 2217000,
			'Latvia': 2070371,
			'Slovenia': 2057880,
			'Macedonia': 2057284,
			'Botswana': 2038228,
			'Gambia': 1825000,
			'Qatar': 1699435,
			'Guinea-Bissau': 1580000,
			'Gabon': 1564000,
			'Trinidad and Tobago': 1317714,
			'Estonia': 1294236,
			'Mauritius': 1286051,
			'Bahrain': 1234571,
			'Swaziland': 1220000,
			'Timor-Leste': 1066409,
			'Djibouti': 923000,
			'Fiji': 876000,
			'Réunion':  865000,
			'Cyprus': 838897,
			'Guyana': 784894,
			'Comoros': 773000,
			'Equatorial Guinea': 740000,
			'Bhutan': 720679,
			'Montenegro': 620029,
			'Macau':  557400,
			'Solomon Islands': 553935,
			'Western Sahara': 567000,
			'Suriname': 534000,
			'Luxembourg': 511800,
			'Cape Verde': 491875,
			'Guadeloupe':  465000,
			'Brunei': 422700,
			'Malta': 417617,
			'Martinique':  408000,
			'Bahamas': 353658,
			'Iceland': 320060,
			'Maldives': 317280,
			'Belize': 312971,
			'Barbados': 274200,
			'French Polynesia':  277000,
			'New Caledonia':  259000,
			'Vanuatu': 252000,
			'French Guiana':  243000,
			'Mayotte':  217000,
			'Samoa': 186340,
			'São Tomé and Príncipe': 172000,
			'Saint Lucia': 166526,
			'Guam':  159358,
			'Curaçao': 149679,
			'Saint Vincent and the Grenadines': 109000,
			'United States Virgin Islands':  106405,
			'Grenada': 105000,
			'Tonga': 103036,
			'Federated States of Micronesia': 102624,
			'Aruba': 101484,
			'Kiribati': 101000,
			'Jersey':  97857,
			'Seychelles': 90945,
			'Antigua and Barbuda': 86295,
			'Isle of Man':  84497,
			'Andorra': 78115,
			'Dominica': 71293,
			'Bermuda':  64237,
			'Guernsey':  62431,
			'Greenland':  56749,
			'American Samoa':  55519,
			'Cayman Islands':  55456,
			'Marshall Islands': 54305,
			'Saint Kitts and Nevis': 54000,
			'Northern Mariana Islands':  53883,
			'Faroe Islands':  48285,
			'Turks and Caicos Islands':  44493,
			'Sint Maarten': 37429,
			'Saint Martin':  36824,
			'Liechtenstein': 36476,
			'Monaco': 35881,
			'San Marino': 32312,
			'Gibraltar':  29441,
			'Åland Islands':  28355,
			'British Virgin Islands':  24000,
			'Caribbean Netherlands': 21133,
			'Palau': 21000,
			'Cook Islands':  17791,
			'Anguilla':  15236,
			'Wallis and Futuna':  13000,
			'Nauru': 10000,
			'Tuvalu': 10000,
			'Saint Barthélemy':  8902,
			'Saint Pierre and Miquelon':  6000,
			'Montserrat':  4922,
			'Saint Helena, Ascension and Tristan da Cunha':  4000,
			'Falkland Islands':  3000,
			'Svalbard and Jan Mayen':  2495,
			'Norfolk Island':  2302,
			'Christmas Island':  1462,
			'Tokelau':  1411,
			'Niue':  1000,
			'Vatican City': 800,
			'Cocos (Keeling) Islands':  605,
			'Pitcairn Islands':  66
		};

		// Create custom key-pair lookup table
		var codes = {};
		for(i=0;i<countries.length;i++) {
			codes[countries[i].name.toLowerCase()] = countries[i].code.toLowerCase();
		}

		// Grab Olympic Data
		$.ajax({
			url: 'http://apify.heroku.com/api/olympics2012_medals.json',
			dataType: 'jsonp',
			success: function(data){

				// Parse returned JSON
				data = $.parseJSON(data);

				// Set DOM manipulation completion variable
				var complete = false;

				// Loop over each country up to 20
				for(i=0; i<data.length; i++) {

					// Create all necessary DOM elements and calculate statistics
					var cur = data[i],
						row = $('<tr class="row"></tr>').css("display", "none").appendTo('.table tbody'),
						country = $('<td class="country"><img class="flag" src="img/' + codes[cur.country.replace('c  ', 'c ').toLowerCase()] + '.png" /><span class="country name">' + cur.country + '</span></td>').appendTo(row),
						golds = $('<td class="golds">' + cur.gold + '</td>').appendTo(row),
						silvers = $('<td class="silvers">' + cur.silver + '</td>').appendTo(row),
						bronzes = $('<td class="bronzes">' + cur.bronze + '</td>').appendTo(row),
						medals = $('<td class="medal">' + cur.total + '</td>').appendTo(row),
						perMil = $('<td class="stat">' + (cur.total / (population[cur.country.replace('c  ', 'c ')] / 1000000)).toFixed(8) + '</td>').appendTo(row);
					
					// If i has reached final value, set DOM manipulation completion variable to true
					if(i === data.length-1) {
						complete = true;
					}
					else {
						complete = false;
					}
				}

				// Check for completion of DOM manipulation every 50ms before sorting table, hiding loading.gif and making rows visible
				var check = setInterval(function(){
					if(complete) {

						// Sort table according to medals per millions, set whole TH to be clickable for sorting
						TableSort.click(0, 2, "num");
						TableSort.click(0, 2, "num");

						// Show rows, hide loading.gif
						$('.row').show('slow');
						$('.loading').hide('slow');

						// Stop repeating
						clearInterval(check);
					}
					else {
						console.log('Not yet.');
					}
				},50);
			}
		});

	});

})(jQuery);